// Content scraped from kagankans.com
window.SITE = {
  name: "Daniel Kagan-Kans",
  bio: "I write about AI, science, and culture for publications including The Wall Street Journal and The New York Times. I'm from Maryland, live in New York, and was previously managing editor at Mosaic.",
  email: "dkagankans@gmail.com",
  twitter: { handle: "@kagankans", url: "https://x.com/kagankans" },
  agent: { name: "Sarah Fuentes, UTA", email: "sarah.fuentes@unitedtalent.com" },
  recent: [
    {
      title: "The Data Center Is a Symbol",
      pub: "Transformer",
      year: "2026",
      desc: "The claims about water and energy are mostly wrong. The feeling underneath them is not.",
      url: "https://www.transformernews.ai/p/the-data-center-is-a-symbol",
    },
    {
      title: "Hans Moravec Was Right About AI. What About the Fate of Mankind?",
      pub: "New York",
      year: "2026",
      desc: "The reclusive roboticist predicted human-level AI by 2028. Now he contemplates our species’ end—and his own.",
      url: "https://nymag.com/intelligencer/article/hans-moravec-interview.html",
    },
    {
      title: "How 6,000 Bad Coding Lessons Turned a Chatbot Evil",
      pub: "The New York Times",
      year: "2026",
      desc: "What emergent misalignment in AI might tell us about virtue ethics and human character.",
      url: "https://www.nytimes.com/2026/03/10/opinion/ai-chatbots-virtue-vice.html",
    },
    {
      title: "The Left Is Missing Out on AI",
      pub: "Transformer",
      year: "2026",
      desc: "By refusing to engage seriously with AI, the movement is giving up a crucial chance to participate in the world's future.",
      url: "https://www.transformernews.ai/p/the-left-is-missing-out-on-ai-sanders-doctorow-bender-bores",
    },
    {
      title: "Baby Shoggoth Is Listening",
      pub: "The American Scholar",
      year: "2025",
      desc: "Why some people are starting to write for AI readers, and what happens when they do.",
      url: "https://theamericanscholar.org/baby-shoggoth-is-listening/",
    },
    {
      title: "The Rise of 'Conspiracy Physics'",
      pub: "The Wall Street Journal",
      year: "2025",
      desc: "On popular YouTube claims that theoretical physicists are scammers in it for the money.",
      url: "https://www.wsj.com/science/physics/the-rise-of-conspiracy-physics-dd79fe36",
    },
    {
      title: "Confessions of an Unphotogenic Man",
      pub: "The Wall Street Journal",
      year: "2024",
      desc: "A light sketch about being unphotogenic.",
      url: "https://www.wsj.com/lifestyle/confessions-of-an-unphotogenic-man-811b97b4",
    },
  ],
  archive: [
    { title: "That Holocaust Feeling", pub: "Mosaic", year: "2016", desc: "On the problems with Son of Saul and the aesthetic temptations of Holocaust cinema.", url: "https://mosaicmagazine.com/essay/arts-culture/2016/03/very-original-very-unusual-very-grotesque-the-problem-with-son-of-saul/" },
    { title: "The Grand Gelinaz! Shuffle", pub: "Kitchen Work", year: "2018", desc: "Inside the global swap that sent the world's best chefs into each other's kitchens for one night.", url: "https://kagankans.com/Grand Gelinaz Shuffle Kitchen Work.pdf" },
    { title: "Beyond Unspeakable", pub: "Prussian Blue", year: "2017", desc: "An essay on photography, atrocity, and the limits of what an image can carry.", url: "https://www.artbook.com/9788416282883.html" },
    { title: "The Beautiful, Miraculous, and Boring Blue Planet", pub: "Vice", year: "2017", desc: "On the strange experience of watching nature documentaries, and what it reveals about the planet we already live on.", url: "https://www.vice.com/en/article/bj54nv/blue-planet-weed-richard-attenborough" },
    { title: "The Redneck Arcadia", pub: "Vice", year: "2016", desc: "The unheralded genius of Trailer Park Boys, and the pastoral tradition it accidentally extends.", url: "https://www.vice.com/en/article/7bmvyy/the-redneck-arcadia-the-unheralded-genius-of-trailer-park-boys" },
    { title: "The Fool and the Assassin", pub: "Jewish Ideas Daily", year: "2013", desc: "On Sholem Aleichem, comic violence, and the literature of powerlessness.", url: "http://www.jewishideasdaily.com/5972/features/the-fool-and-the-assassin/" },
  ],
};
